apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
data:
  mongo-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGItc2VydmljZToyNzAxNy9tdWNodG9kbz9hdXRoU291cmNlPWFkbWlu
